version: '3.7'

networks:
  php-timeline:

services:
  mysql:
    image: mysql
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_DATABASE: timeline
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/timneline
    networks:
      - php-timeline

  php:
    build:
      context: .
    container_name: php
    image: sf-image/php:latest
    restart: on-failure
    environment:
      APP_ENV: prod
    ports:
      - 8000:8000
    depends_on:
      mysql:
        condition: service_started
    networks:
      - php-timeline


    
